# Arctic MMORPG Server Software
# Copyright (c) 2008-2015 Arctic Server Team
# See COPYING for license details.

language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
branches:
  only:
    - master

compiler:
  - gcc
  - clang

script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - sh ./configure
  - /bin/bash ./configure CONFIG_SHELL=/bin/bash
